version: '3.7'
services:
  database:
    image: postgres
    container_name: drugstore
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_drugstore
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=drugstore
    volumes:
      - pdgata:/data/postgres
    expose:
      - 5432
  api:
    build: .
    container_name: drugstore_api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/drugstore_api
      - /drugstore_api/node_modules
    links:
      - database
    depends_on:
      - database

volumes:
  pdgata:
    driver: local
